(define (problem problem_10)
    (:domain vaccine-delivery)
    ;  Household problem file
    (:objects
        n1 n2 - nurse
        hospital house1 house2 house3 house4 house5 house6 house7 house8 - location
        mother1 father1 son1 2son1 daughter1 father2 2father2 daughter2 grandfather3 mother3 son3 daughter3 grandfather4 grandmother4 daughter4 2daughter4 grandmother5 grandfather5 2grandmother5 2grandfather5 mother6 2mother6 grandmother7 daughter7 son7 grandfather8 son8 - person
    )
    (:init
        (vaccineOld n1)
        (vaccineYoung n2)

        (notVaccinated mother1)
        (not (vaccinated mother1))
        (notVaccinated father1)
        (not (vaccinated father1))
        (notVaccinated son1)
        (not (vaccinated son1))
        (notVaccinated 2son1)
        (not (vaccinated 2son1))
        (notVaccinated daughter1)
        (not (vaccinated daughter1))
        (notVaccinated father2)
        (not (vaccinated father2))
        (notVaccinated 2father2)
        (not (vaccinated 2father2))
        (notVaccinated daughter2)
        (not (vaccinated daughter2))
        (notVaccinated grandfather3)
        (not (vaccinated grandfather3))
        (notVaccinated mother3)
        (not (vaccinated mother3))
        (notVaccinated son3)
        (not (vaccinated son3))
        (notVaccinated daughter3)
        (not (vaccinated daughter3))
        (notVaccinated grandfather4)
        (not (vaccinated grandfather4))
        (notVaccinated grandmother4)
        (not (vaccinated grandmother4))
        (notVaccinated daughter4)
        (not (vaccinated daughter4))
        (notVaccinated 2daughter4)
        (not (vaccinated 2daughter4))
        (notVaccinated grandmother5)
        (not (vaccinated grandmother5))
        (notVaccinated grandfather5)
        (not (vaccinated grandfather5))
        (notVaccinated 2grandmother5)
        (not (vaccinated 2grandmother5))
        (notVaccinated 2grandfather5)
        (not (vaccinated 2grandfather5))
        (notVaccinated mother6)
        (not (vaccinated mother6))
        (notVaccinated 2mother6)
        (not (vaccinated 2mother6))
        (notVaccinated grandmother7)
        (not (vaccinated grandmother7))
        (notVaccinated daughter7)
        (not (vaccinated daughter7))
        (notVaccinated son7)
        (not (vaccinated son7))
        (notVaccinated grandfather8)
        (not (vaccinated grandfather8))
        (notVaccinated son8)
        (not (vaccinated son8))

        (not (carryingVaccine n1))
        (notCarryingVaccine n1)

        (not (carryingVaccine n2))
        (notCarryingVaccine n2)

        (isPickUpLocation hospital)

        (at n1 hospital)
        (at n2 hospital)

        (atPerson mother1 house1) 
        (atPerson father1 house1) 
        (atPerson son1 house1) 
        (atPerson 2son1 house1) 
        (atPerson daughter1 house1) 
        (atPerson father2 house2) 
        (atPerson 2father2 house2) 
        (atPerson daughter2 house2) 
        (atPerson grandfather3 house3) 
        (atPerson mother3 house3) 
        (atPerson son3 house3) 
        (atPerson daughter3 house3) 
        (atPerson grandfather4 house4) 
        (atPerson grandmother4 house4) 
        (atPerson daughter4 house4) 
        (atPerson 2daughter4 house4) 
        (atPerson grandmother5 house5) 
        (atPerson grandfather5 house5) 
        (atPerson 2grandmother5 house5) 
        (atPerson 2grandfather5 house5) 
        (atPerson mother6 house6) 
        (atPerson 2mother6 house6) 
        (atPerson grandmother7 house7) 
        (atPerson daughter7 house7) 
        (atPerson son7 house7) 
        (atPerson grandfather8 house8) 
        (atPerson son8 house8)

        (connected house1 house2)
        (connected house2 house1)
        (connected house2 house4)
        (connected house4 house2)
        (connected house2 house5)
        (connected house5 house2)
        (connected house3 house4)
        (connected house4 house3)
        (connected house3 house6)
        (connected house6 house3)
        (connected house4 house8)
        (connected house8 house4)
        (connected house5 house7)
        (connected house7 house5)
        (connected house6 house7)
        (connected house7 house6)
        (connected house7 house8)
        (connected house8 house7)

        (connected hospital house1)
        (connected house1 hospital)
        (connected hospital house3)
        (connected house3 hospital)
        (connected hospital house7)
        (connected house7 hospital)

        (not (under60 mother1))
        (over60 mother1)
        (not (under60 father1))
        (over60 father1)
        (under60 son1)
        (not (over60 son1))
        (under60 2son1)
        (not (over60 2son1))
        (under60 daughter1)
        (not (over60 daughter1))
        (under60 father2)
        (not (over60 father2))
        (not (under60 2father2))
        (over60 2father2)
        (under60 daughter2)
        (not (over60 daughter2))
        (not (under60 grandfather3))
        (over60 grandfather3)
        (not (under60 mother3))
        (over60 mother3)
        (not (over60 son3))
        (under60 son3)
        (not (over60 daughter3))
        (under60 daughter3)
        (not (under60 grandfather4))
        (over60 grandfather4)
        (not (under60 grandmother4))
        (over60 grandmother4)
        (not (over60 daughter4))
        (under60 daughter4)
        (not (over60 2daughter4))
        (under60 2daughter4)
        (not (under60 grandmother5))
        (over60 grandmother5)
        (not (under60 grandfather5))
        (over60 grandfather5)
        (not (under60 2grandmother5))
        (over60 2grandmother5)
        (not (under60 2grandfather5))
        (over60 2grandfather5)
        (not (under60 mother6))
        (over60 mother6)
        (under60 2mother6)
        (not (over60 2mother6))
        (not (under60 grandmother7))
        (over60 grandmother7)
        (under60 daughter7)
        (not (over60 daughter7))
        (under60 son7)
        (not (over60 son7))
        (not (under60 grandfather8))
        (over60 grandfather8)
        (under60 son8)
        (not (over60 son8))
    )

    (:goal
        (and
            (at n1 hospital)
            (at n2 hospital)
            (vaccinated mother1)
            (vaccinated father1)
            (vaccinated son1)
            (vaccinated 2son1)
            (vaccinated daughter1)
            (vaccinated father2)
            (vaccinated 2father2)
            (vaccinated daughter2)
            (vaccinated grandfather3)
            (vaccinated mother3)
            (vaccinated son3)
            (vaccinated daughter3)
            (vaccinated grandfather4)
            (vaccinated grandmother4)
            (vaccinated daughter4)
            (vaccinated 2daughter4)
            (vaccinated grandmother5)
            (vaccinated grandfather5)
            (vaccinated 2grandmother5)
            (vaccinated 2grandfather5)
            (vaccinated mother6)
            (vaccinated 2mother6)
            (vaccinated grandmother7)
            (vaccinated daughter7)
            (vaccinated son7)
            (vaccinated grandfather8)
            (vaccinated son8)
        )
    )
)